- apriltag.c
maybe you the definition in your apriltag3 is not the same as version2; so the logical of the fixed code may be contrary
> Fixrotate90

- tag16h5.c
- tag25h9.c
- tag36h11.c
- tagCircle21h7.c
- tagCircle49h12.c
- tagCustom48h12.c
- tagStandard41h12.c
- tagStandard52h13.c
There is code 
`tf->name = strdup("tag25h9");`
in each tag family implementation. According to specification of `strdup` function (https://en.cppreference.com/w/c/experimental/dynamic/strdup) the pointer returned by it should be freed by user of the function. But tag_family_destroy does not do it. It leads to tiny memory leak (about 9 byte each) but still.
I assume that those changes should be done also in generator of families implementation.
> Tiny memory leak in tag families implementation

- .gitignore
- CMakeLists.txt
- apriltag.pc.in
- package.xml
This PR adds support for the CMake build system and pkg-config. This enables the library to be used in other CMake projects. I also added a `package.xml` with metadata about the library. It is commonly used by other build systems (e.g. catkin and colcon for ROS1 and ROS2) to track build dependencies.
I used to maintain this in a separate git repository at https://github.com/christianrauch/apriltag2 before the AprilTags library moved to a versioning system. I would like to have this merged upstream to ease updates of the library and the use in other build systems.
> CMake support

- CMakeLists.txt
This PR exports the `apriltag` library for other cmake projects.
One can use the library in other cmake projects by adding these two lines:
```CMake
find_package(apriltag REQUIRED)
target_link_libraries(<your_project> apriltag)
```
The include and library directories are automatically added by the exported properties.
> export project

- apriltag_pose.c
`pose2.R` is initialized only if there is one new minima:
https://github.com/AprilRobotics/apriltags/blob/a5ab81dd79fd294b77940efad889a820509e83ae/apriltag_pose.c#L412-L426
`pose2.t` is initialized only if `pose2.R` is not `NULL`:
https://github.com/AprilRobotics/apriltags/blob/a5ab81dd79fd294b77940efad889a820509e83ae/apriltag_pose.c#L496-L502
Probably should fix #22
> Check for NULL before calling matd_destroy

- example/opencv_demo.cc
Fixed a little bug that would cause memory leaks.
> Correctly deallocate detections in opencv demo

- .travis.yml
- README.md
This PR adds continuous integration using Travis which will run build (using catkin which internally uses the CMake build) at every push/PR. This PR uses ROS-Industrial CI which also tests whether the package can be released (by running the pre-release tests). 
Example output from my fork: https://travis-ci.com/wxmerkt/apriltag/builds/108943931
This will require activating Travis for the repository/organisation manually after this PR has been merged.
> Add Travis CI using ROS-Industrial CI

- CMakeLists.txt
- package.xml
Now that the ROS wrapper update is merged, I am intending to progress with releasing the library via bloom in order to release `apriltag_ros`. 
To receive the status emails, I have added myself as a maintainer. @mkrogius, if you go ahead with merging this PR, can you please tag the post-merge master to `3.1.0`?
Related to #16
> Set version to 3.1 and add myself as maintainer for bloom release

- common/matd.h
This prevents compilation errors when including apriltag headers into external libraries which have -Werror and -Wall enabled.
> Added a cast from int to unsigned int in common/matd.h

- apriltag.c
- apriltag_pose.c
- apriltag_quad_thresh.c
- common/pjpeg.c
- common/string_util.c
- common/zhash.c
Example:
```
warning: declaration of ‘entry_idx’ shadows a previous local [-Wshadow]
for (int entry_idx = 0; entry_idx < zh->nentries; entry_idx++) {
^
```
and
```
warning: argument to ‘sizeof’ in ‘memset’ call is the same expression as the destination; did you mean to dereference it? [-Wsizeof-pointer-memaccess]
memset(dcpred, 0, sizeof(dcpred));
^
```
> Fix warnings detected with -Wsizeof-pointer-memaccess and -Wshadow

- CMakeLists.txt
The build failed if `-DCMAKE_C_FLAGS` is set in cmake command. Here is an example command
```
"cmake" ".." "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sect
ions -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=Debug"
```
I dumped `make VERBOSE=1`. It shows that the space in `CMAKE_C_FLAGS` is escaped in command line. This is due to the rule of add\_custom\_command [here](https://github.com/AprilRobotics/apriltag/blob/cad1009f9fbf457e2a5393c0fb6c8a05042a0611/CMakeLists.txt#L86).
```
[ 87%] Generating apriltag_pywrap.o
/usr/bin/cc \ -ffunction-sections\ -fdata-sections\ -fPIC\ -m64 -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -Wall -march=x86-64 -mtune=generic …
```
> Remove space-separated CMAKE_C_FLAGS in add_custom_command

- CMakeLists.txt
This pull request improves the build system on two points:
* Uses PROJECT_SOURCE_DIR instead of CMAKE_SOURCE_DIR : When trying to build apriltag using cmake `ExternalProject_Add` or `FetchContent`, the python and tags macros fails, as `CMAKE_SOURCE_DIR` refers to the parent's project directory and not apriltag's project directory.
*  Makes the python wrapper build optional. Just add an option to hide any message warning in automated build system if one is not interested in python wrapper. The default behavior is conserved
> Improves build system for edge cases.

- CMakeLists.txt
If apriltag is installed locally and `~/.local/lib/python3.6` does not exist, the installation will fail with: `cp: cannot create regular file '/home/ubuntu/.local/lib/python3.6/site-packages': No such file or directory`. 
This is caused by
https://github.com/AprilRobotics/apriltag/blob/cad1009f9fbf457e2a5393c0fb6c8a05042a0611/CMakeLists.txt#L96
since files are simply copied via the `cp` command, which does not automatically create the file structure.
This PR installs this file via https://cmake.org/cmake/help/v3.13/command/install.html#installing-files which creates the necessary file hierarchy.
> use FILES rules to install python wrapper

- CMake/apriltagConfig.cmake
- CMake/apriltagConfig.cmake.in
- CMakeLists.txt
Here are few fixes and refactoring of the CMakeLists file to make the export more standard (in terms of modern cmake).
* add version and languages to project() so the library version can be defined once and then used as ${PROJECT_VERSION}
* Added two options:
* Standard BUILD_SHARED_LIBS (Default ON) to enable building shared or static libs
* CMAKE_BUILD_TYPE will default to release if not specified
* removed `include_directory()`, its use is not recommended in modern cmake, better use per target includes.
* add a debug postfix when the library is built in debug (it adds the standard "d" at the end of the name)
* refactoring of the install/export of cmake config files, most notably
* the config file is now parametric and generated automatically
* a version file is generated to allow …
> [cmake] install fixes and refactoring

- apriltag_quad_thresh.c
Hello,
I found myself in a case where `nclustermap < mem_chunk_size` resulting in `sizeof(struct uint64_zarray_entry *)*2*nclustermap/mem_chunk_size == 6`, which is not a multiple of the size of pointer!
At least the code should be:
`malloc(sizeof(struct uint64_zarray_entry *)*(2*nclustermap/mem_chunk_size));`
in order to ensure we get an integer amount of pointer.
I made the following patch, since it appears that we at least need a size of 1:
`malloc(sizeof(struct uint64_zarray_entry *)*(1 + 2 * nclustermap / mem_chunk_size));`
> Fix memory corruption on mem_pools in do_gradient_clusters() 

- CMake/apriltagConfig.cmake.in
In order to maintain backwards compatibility with versions 3.1.2 and earlier where target "apriltag" existed, add an ALIAS target to the new target with namespace ("apriltag::apriltag") introduced in commit 35f4ef2
This is a potential solution to unblock a release (#166)
> Add ALIAS target "apriltag" for "apriltag::apriltag" to achieve backwards compatibility

- CMake/apriltagConfig.cmake.in
IMPORTED_GLOBAL is only available in CMake 3.11 and newer. Ubuntu 18.04
ships with CMake 3.10 and thus failed to configure projects using
AprilTag v3.15. This fix only activates the backwards-compatible ALIAS
target when using a new, supported CMake version.
> Fix for #167 for CMake versions <3.11

- CMakeLists.txt
Respects the BUILD_SHARED_LIBS options to enable static builds if desired. Also disables the build of the python wrapper when building statically. This should remain compatible with any current build workflows.
> Optionally build static version

- common/matd.c
Hello,
I happened to fall on this potential memory leak browsing your code.
We assign `v` line 1088: `double *v = malloc(sizeof(double)*vlen);`.
It seems that we never free it if `mag == 0`.
I thought you might like a PR. Feel free to use it or not.
Thanks a lot for your work and for your time! :)
> Fixed a memory leak in matd_svd_tall

- README.md
- documents the use of `BUILD_SHARED_LIBS` for building either shared or static libraries
- optionally uses Ninja to build (it's much faster -- 2.2s (ninja) vs. 7.6s (make) on my system)
- uses `cmake --build build` to build build-system-agnostic
- build in separate `build` directory to not interfere with source files and the legacy `Makefile`
> update cmake documentation

- CMakeLists.txt
Build with `-DASAN=ON` to enable AddressSanitizer. Memory issues will be shown on screen.
Some backtraces will be shortened. Run with
`ASAN_OPTIONS=fast_unwind_on_malloc=0 <exec>`
to show full backtrace.
> build with AddressSanitizer to find memory issues

- CMakeLists.txt
- example/Makefile
- package.xml
This switches the Makefile to use OpenCV 4 and also sets the include path correctly via `pkg-config --cflags`.
> switch to OpenCV4

- common/unionfind.h
Parameter type is a uint32_t, causes compiler warning.
> Fixing compiler warning in unionfind.h for maxint

- example/apriltag_demo.c
./apriltag_demo ~/Downloads/nori-5-640.jpg --decimate=0 --blur=5 --debug --threads=8
loading /Users/jacob.repp/Downloads/nori-5-640.jpg
image: /Users/jacob.repp/Downloads/nori-5-640.jpg 480x640
0                             init        0.007000 ms        0.007000 ms
1                       blur/sharp       32.702000 ms       32.709000 ms
2                        threshold        6.013000 ms       38.722000 ms
3                        unionfind       13.113000 ms       51.835000 ms
4                    make clusters        6.358000 ms       58.193000 ms
5            fit quads to clusters       30.752000 ms       88.945000 ms
6                            quads        0.216000 ms       89.161000 ms
7                decode+refinement        6.644000 ms       95.805000 ms
8 …
> Updating apriltag demo with image statistics (path and size)

- apriltag.c
When failing to solve the quad homography solution exit the function with a NULL and handle the failure in the caller.
This prevents writing to invalid memory locations later in the function.
Note that the trigger for this is a NaN earlier in line building. There may be some degenerate cases in the eigenvalue solve for line building that needs additional testing.
This change does not introduce any regressions to positive test cases.
See: 
https://github.com/AprilRobotics/apriltag/issues/72
https://github.com/AprilRobotics/apriltag/issues/154
> Safely fail homography building when failing row swap

- CMakeLists.txt
Building with sanitizers is not currently working because the code is C and the flags are set for CXX instead.
Just need to use `CMAKE_C_FLAGS_DEBUG`
> [cmake] sanitazier flags in C_FLAGS instead of CXX

- common/zhash.c
```../common/zhash.c:545:22: runtime error: left shift of 211382645 by 7 places cannot be represented in type 'int'```
Fixed the ASAN error
Noticed the hash was lacking so improved the string hash function to use an optimized [FNV](https://en.wikipedia.org/wiki/Fowler%E2%80%93Noll%E2%80%93Vo_hash_function) - it's a few more hashes and a multiply.
Currently, this str hash is only used to index command-line arguments.
> Fixing zhash/ASAN errors, improve hash

- README.md
Thanks to https://github.com/AprilRobotics/apriltag/pull/215, the `AddressSanitizer` feature now works properly. I added documentation on how to enable and use it. Using these instructions, the `opencv_demo` example already reports numerous `runtime error: division by zero` errors.
> add documentation on how to enable and use the AddressSanitizer

- CMakeLists.txt
The -ftlo can lead to issues when linking for system libraries compiled with a different compiler version.
See #227 
If the flag is not part of `PY_CFLAGS` it has no effects (tested with cmake version 3.10.2).
> [cmake] Remove -ftlo flag from PY_CFLAGS

- apriltag.c
- apriltag_pose.c
- apriltag_pywrap.c
- common/debug_print.h
- common/g2d.c
- common/matd.c
- common/workerpool.c
- common/zmaxheap.c
- example/apriltag_demo.c
- example/opencv_demo.cc
Here is a belated PR for issue #182.
I have removed all the calls to `exit()` that might be encountered and set the `errno` where it isn't already set by the operation that failed.
As the user might not be checking the `errno` values I thought it best to avoid their application crashing by returning an empty detections array, where relevant, to avoid them encountering a null-pointer.
Any feedback is welcome and I am happy to tweak as required.
> Replaced calls to exit()

- .github/workflows/industrial_ci_action.yml
- .github/workflows/ros_workspace.yml
- CMakeLists.txt
- common/workerpool.c
- example/opencv_demo.cc
We need to define `_GNU_SOURCE` for the initially reported error to go away. 
Since Ubuntu 16.04 ships by default with OpenCV 2.4, we need further changes for renamed variables and moved modules (`TickMeter` was in `contrib` back in 2.4).
Resolves #244
> Add back Ubuntu 16.04 support - resolves #244

- apriltag_pywrap.c
This is to solve Issue #243. The functionality was already there, but "refine-edges" can't be used as a keyword argument in python because of the '-'.
> Fixed refine_edges keyword to allow it to be referenced in Python

- CMakeLists.txt
- apriltag.c
- apriltag.h
- apriltag_quad_thresh.c
- package.xml
Some of the `apriltag_detector_t` parameters are meant to be used as binary flags but stored as an integer with a much larger value range. This makes it difficult from an API perspective to directly grasp the meaning of a parameter. I am proposing here to change the type of `refine_edges`, `debug` and `qtp.deglitch` from `int` to `bool`.
While this is an API change, the impact should be low since previously used `int`s should be cast automatically for `bool`en values.
> declare binary parameters as bool

- CMakeLists.txt
- apriltag.pc.in
I noticed that the version on the `apriltag.pc` file was hard coded. CMake provides `configure_file` to format such a file automatically, including the version.
> version the pkg-config file and use standard CMake for formatting

- CMakeLists.txt
- package.xml
Noticed that the OpenCV demo wasn't configured despite OpenCV being installed since the `contrib` module wasn't found.
> Fix OpenCV configuration

- CMakeLists.txt
- example/opencv_demo.cc
When looking into https://github.com/AprilRobotics/apriltag/issues/253 I noticed that the AddressSanitizer is not enabled for C++ code. This is only relevant for the `opencv_demo`.
This PR uses the same ASAN flags for C and C++ code and for Debug as well as Release builds. While at it, I fixed some of the whitespace issues and added an additional configuration flag `-c` to select the camera to use.
Regarding the actual memory leaks, there are some leaks in `libfontconfig.so`. But overall, this seems to be constant. No matter how long I let the `opencv_demo` run without showing an actual tag, ASan will report `SUMMARY: AddressSanitizer: 43736 byte(s) leaked in 812 allocation(s).`.
However, ASan reported some `division by zero` errors which may be related to …
> enable ASan for C++

- apriltag_quad_thresh.c
In other chunks of work split into thread pools, the work is split up more finely than the number of CPUs.  This makes it so that if a thread gets behind (in a big.little architecture, this is expected, or in the case of preemption), the threads that are ahead can pick up the extra work.
gradient_clusters was missing this split.  This saved 5-10ms of processing time on my Rock Pi 4b and reduced the outliers.
> Split work up in gradient_clusters more finely

- CMakeLists.txt
I have a customized OpenCV install that caused the opencv example build to fail. I've added an cmake option to allow users to optionally disable building the examples.
> Added a cmake option for building example executables

- apriltag_quad_thresh.c
- common/zarray.h
I was looking through the code and found that a lot of time was being spent on 'make clusters' so I did a quick look through why that is the case. I found the merge_clusters function to be inefficient, so I optimized it to do batch memcopies wherever possible.
This gives me a ~20% reduction in time spent for a large image.
> Speed up cluster merge by batch copying arrays

- apriltag_pywrap.c
I was stunned for a while when using Python wrapper, because the behavior was different from that of C.
Specifically, when the image is blurry and noisy (bad lighting & bad focus), and a tag is close enough so that it takes a good portion of an image, the Apriltag detection fails for Python wrapper, while the original C implementation manages to detect it nevertheless.
The problem was that the default decimation value was 2.0 for C, and 1.0 for Python wrapper.
As having different default behavior can be deceiving to many, and is counter-intuitive, I open this PR.
> change default decimation parameter for python wrapper

- common/getopt.c
- common/pam.c
- common/string_util.c
In getopt.c, the variable pos was of type int and this comparison to the len variable, which is of type size_t, presents a security vulnerability for my team's utilization of this repository as pos is of a different type than len. I changed the pos variable to be of type size_t to enable pos and len to be consistently compared in the for loop where "pos < len". Similarly, in string_util.c, pos and haystack_len are compared as inconsistent types so to address this security vulnerability, I changed pos to be of type size_t. In pam.c, I changed idx to be of type size_t to address the same security vulnerability as for the files above.
> Changed type to size_t for consistent type comparison

- common/unionfind.h
I figured out that a big part of the union find time spent was initializing the data array. I've optimized it by using two `memset`s instead of an array, which saves ~4% for an image sized 4896×3264
> Optimize unionfind

- README.md
Add missing `apriltag_detections_destroy()` call. Fix #246
> fix incorrect C example #246

- CMakeLists.txt
When building apriltag as a shared library on Windows, the DLLs could be installed in the bin folder, where the variable PATH should be properly configured, resulting in no problems at runtime.
Reference: https://cmake.org/cmake/help/latest/command/install.html#signatures
> CMake install: Set .dll location to bin folder

- apriltag_quad_thresh.c
In quad_segment_maxima, nothing uses params23 and params30, but these are calculated anyways.  The compiler isn't smart enough to know that there are no side effects, so it doesn't skip calculating them.
On my test box, this takes
fit quads to clusters        8.896000 ms       23.968000 ms
to
fit quads to clusters        8.429000 ms       23.490000 ms
which is measurable.
> Speed up quad_segment_maxima by skipping unneeded lineparam calculation.

- apriltag_quad_thresh.c
It was being used as a mse, and passed into fit_line in the mse position.  Let's make the name match.
> Rename missnamed err to mse.

- .github/workflows/industrial_ci_action.yml
- CMakeLists.txt
- apriltag.c
- apriltag.h
- apriltag_quad_thresh.c
- common/getopt.c
- common/homography.c
- common/homography.h
- common/image_u8.c
- common/image_u8x3.c
- common/image_u8x3.h
- common/matd.c
- common/matd.h
- common/pam.c
- common/pam.h
- common/pjpeg.c
- common/string_util.c
- common/string_util.h
- common/zmaxheap.c
- example/opencv_demo.cc
- package.xml
This PR enables and fixes a couple of warnings throughout the code base. All warnings are reported as errors to make sure that those are not introduced again.
Note: This PR removes unused parameters from function declarations and therefore breaks API with the previous version (3.3). Therefore, the next release has to bump the minor version.
> fix warnings

- apriltag_quad_thresh.c
The segmentation system was adding duplicate points to the clusters list before removing them later.
This has 2 problems.
1) It is more expensive to remove them later than not to add them.
2) When sorting, multiple slopes can have the same calculated slope
value.  Depending on the initial order, the duplicates can end up
being in non-adjacent slots in the cluster, and won't get
de-duplicated later.
This takes my sample image on my test box from:
0                             init        0.000000 ms        0.000000 ms
1                         decimate        0.292000 ms        0.292000 ms
2                       blur/sharp        0.000000 ms        0.292000 ms
3                        threshold        0.617000 ms        0.909000 ms
4                        unionfind        3.746000 ms …
> Stop adding duplicate points to the clusters.

- apriltag.c
- apriltag_quad_thresh.c
This correctly checks for 0 length and determinant and avoids division by zero issues. Supersedes https://github.com/AprilRobotics/apriltag/pull/213 (@jrepp) and fixes https://github.com/AprilRobotics/apriltag/issues/72.
> fix 0 length and determinant

- CMakeLists.txt
Change CMAKE_BINARY_DIR to CMAKE_CURRENT_BINARY_DIR during configuration. This is useful when the project is a subdirectory/ submodule another project (e.g. [apriltags_ros](https://github.com/berndpfrommer/apriltag/tree/ros2)).
> Improve CMakeLists config path by using CMAKE_CURRENT_BINARY_DIR

- CMakeLists.txt
- package.xml
The last release was more than 1 year ago and many performance and compilation improvements have been committed since then. Let's create a new release for this.
The most notable breaking changes are the removal of the Makefile, some changes in the Python bindings installation path and the removal of unused parameters in some public functions which will break API if they are used directly.
I intend to use this release to create new binary package releases for the ROS repo and conda-forge.
> bump minor version to prepare release

- apriltag_pywrap.c
Another Python module may set the errno but not inform the user about an error. This will affect the errno checking in the Python bindings `apriltag_new` and `apriltag_detect`. Avoid this by resetting errno at the beginning of those functions.
Fixes #320 .
> reset errno at the beginning of Python function that check it in the end

- apriltag.c
- common/image_u8.c
When the "Find best row to swap with." section in `homography_compute2` would not find a value greater than 0 in a row, `max_val_idx` would stay `-1` and maybe be used later to index a matrix. We protected against the negative indexing (in debug mode) by checking for a positive index in 3a0a155d5bc3bdcef34275f7c51f56e9cfd34e13.
But this causes issues for false-positive quad detections (#321). In this particular case, ignoreing the negative index would lead to `return NULL;` via `max_val < epsilon`, so we can also just `return NULL;` here and ignore that quad instead of stopping the process.
Fixes #321 .
@mkrogius As far as I understand `c[4][4]` contains the 4 correspondences from the 2D pixel coordinates in the image to the 2D coordinates of the unit square with +/-1 edge coordinates. …
> fix homography assert

- .github/workflows/colcon-workspace.yml
- CMakeLists.txt
- package.xml
This sets up the CI and fixes some errors and warnings for the upcoming ROS release "jazzy" on Ubuntu 24.04. I am incrementing the patch version for a new bloom release to "rolling".
> prepare for ROS "Jazzy"

- .github/workflows/bloom.yml
- CMakeLists.txt
- common/matd.c
- package.xml
Even the Ubuntu 24.04 CI https://github.com/AprilRobotics/apriltag/pull/327 could not reproduce some of the "may be used uninitialized" errors that caused blooming failures on the ROS build farm. This PR now directly adds blooming tests to the CI so we can catch these kinds of build issues before releasing a package via bloom.
> test blooming on the CI

- apriltag_py_type.docstring
This prevents confusion since `Nthreads` is an invalid keyword 
The actual keyword for "Nthreads" is threads
> Changed Nthreads to threads in apriltag_py_type.docstring

- apriltag_quad_thresh.c
If the user supplied quad_decimate value of 0.0, it works in most places, but in apriltag_quad_thresh, it led to undefined behavior after dividing by this value.
The symptoms are the triciker that on x86/GCC, the undefined behavior leads to -INT_MAX, which gets corrected to 3 pixels by the following lines of code. However, on arm64/GCC, it results in +INT_MAX, which does not get corrected and leads to a running detector which will never detect anything.
> apriltag_quad_thresh: Prevent conversion from NaN to int

- common/workerpool.c
Looks like a typo to me.
---
There is no `WIN32` macros (at least with usual compilers):
- http://jdebp.info/FGA/predefined-macros-platform.html
- https://learn.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170
- https://sourceforge.net/p/predef/wiki/OperatingSystems/
- http://docwiki.embarcadero.com/RADStudio/Athens/en/Predefined_Macros
> Use _WIN32 macro everywhere

- common/workerpool.c
I encountered random segfaults while using this library and tried to figure out what was happening. I isolated the segfault to the function `worker_thread()` of `workerpool.c`. Long story short, there is no predicate that prevents `worker_thread()` from running if it is woken up spuriously and a task has already been added. Since there is no mutex used in `workerpool_add_task()`, it is possible for the zarray `wp->tasks` to be reallocated, rendering the volatile pointer `task` in `worker_thread()` invalid and causing a segfault.
This PR addresses this issue by adding a predicate and shielding calls that access `wp` behind a mutex. I also saw issue #70 and agree that the initialization of the worker threads might lead to race conditions, so I addressed that too.
> Fix spurious wake-ups and worker threads initialization in workerpool

- tag36h10.c
File https://github.com/AprilRobotics/apriltag/blob/188c0e025d13a607c07d294ac40be604d6598974/tag36h10.c does not have a copyright header.
> Add missing copyright header in tag36h10.c file

- README.md
The C example tried to load a `.png` file with a method for loading `.pnm` files. This will fail and return `NULL` which later causes a segfault.
> Fix README C example

- .github/workflows/cmake-multi-platform.yml
- .github/workflows/cmake-ubuntu.yml
- CMakeLists.txt
- test/CMakeLists.txt
Per CMake documentation, this should be called in the top-level CMakeLists.txt so that testing is enabled for the _project_, and not a subdirectory thereof. This will allow tools like colcon to discover the tests.
> Call enable_testing() in top-level project

- CMakeLists.txt
- common/matd.c
- common/matd.h
The original way of writing `matd_t` was
```c
typedef struct
{
unsigned int nrows, ncols;
double data[];
//    double *data;
} matd_t;
```
which does not conform to the ISO standard. For example, it will generate a warning in C++ compilers such as g++, with the following message:
```
/path/to/apriltag/common/matd.h:48:12: warning: ISO C++ forbids flexible array member ‘data’ [-Wpedantic]
48 |     double data[];
|            ^~~~
```
Therefore, it was changed to use `double *`, and separate memory was allocated for `m` and `m->data`. Additionally, resource release for `m->data` was added in the `matd_destroy` function.
> Modify the memory allocation method of `matd_t` to comply with ISO standards

- CMakeLists.txt
As an architecture-specific CMake project, the CMake config files should be installed to an architecture-specific location.
This issue was identified during the process of packaging `apriltag` for inclusion in Fedora Linux and EPEL[1]. You can see a similar patch was added to the debian build process for Ubuntu[2].
Related docs: https://cmake.org/cmake/help/latest/command/find_package.html#config-mode-search-procedure
[1] https://bugzilla.redhat.com/show_bug.cgi?id=2173758#c17
[2] https://salsa.debian.org/science-team/apriltag/-/blob/master/debian/patches/cmake-into-arch-specific-path.patch
> Install CMake config to architecture-specific location

- README.md
The current coordinate system text is vague. It's unclear if "to the right" refers to the tag's own right or the viewer's right when viewed from the front.
This change clarifies that the X-axis is to the viewer's right when viewed from the front and eliminates that ambiguity.
> Add clarity to tag coordinate system reference frame in README

- common/time_util.h
This PR resolves #296. I changed `windows.h` header for `Winsock2.h`. This way the library still works even when used with `WIN32_LEAN_AND_MEAN` preprocessor definition.
I think even better solution would be to move function `gettimeofday` in `time_util.c` which is the only place where it is used. This way we can also move any required headers (either `windows.h`, `winsock.h` or `Winsock2.h`) from header file which would prevent any side effects to other libraries.
https://github.com/AprilRobotics/apriltag/blob/cc655ad6e3dadb19658276f7476dad5e92f05144/common/time_util.h#L41
> fix compilation with WIN32_LEAN_AND_MEAN

- apriltag_pywrap.c
This PR implements a lock in apriltag_pywrap.c to prevent multiple threads which share the same detector object from calling the detect function, apriltag_detector_detect(), at the same time.
Previously, the Python GIL was released during the call to apriltag_detector_detect(). This would cause the program to crash if multiple threads called this function at the same time. By implementing a lock, only a single thread can call it at a time.
The added functionality was tested using the following Python code:
```Python
from PIL import Image
import threading
import numpy as np
from apriltag import apriltag
image = Image.open("apriltag.png").convert("L")  # Load apriltag image and convert to grayscale.
image_array = np.array(image)
detector = apriltag(
family="tag36h11",
threads=4, …
```
> Acquire Lock Before Releasing Python GIL

- .github/workflows/cross-compilation.yml
- common/time_util.h
When crosscompiling for windows, `Winsock2.h` is not found, because the `include` statement is case sensitive and the header's names is `winsock2.h` instead of `Winsock2.h`.
We now checks which is present and use it.
Also added a workflow to test the cross compilation by building (using mingw) on ubuntu and running the tests on windows.
> fix: windows crosscompilation and added a workflow to test it by crosscompiling on ubuntu and running tests on windows
